---
- name: INSTALL ZABBIX RELEASE FOR REPO TASK
  apt:
#    deb: https://repo.zabbix.com/zabbix/6.2/debian/pool/main/z/zabbix-release/zabbix-release_6.2-1+debian11_all.deb
    deb: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-1%2Bubuntu20.04_all.deb


- name: INSTALL ZABBIX-SERVER TASK
  apt:
    pkg:
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - php7.4-pgsql
    #- php8.1-pgsql
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    update_cache: yes
