---
- name: common
  hosts: gw nginx zabbix
  become: true
  roles:
    - role: common
- name: nginx
  hosts: nginx
  become: true
  roles:
    - role: nginx
    - role: php
    - role: geerlingguy.mysql
    - role: mysql-prepare
    - role: wordpress