---
- name: common
  hosts: gw nginx zabbix
  become: true
  roles:
    - role: common
- name: nginx
  hosts: nginx
  become: true
  roles:
    - role: nginx
    - role: php
    - role: geerlingguy.mysql
    - role: mysql-prepare
    - role: wordpress
- name: zabbix-server
  hosts: zabbix
  become: true
  #zabbix_agent_become_on_localhost: false
  roles:
    - role: geerlingguy.mysql
    - role: geerlingguy.php
    - role: community.zabbix.zabbix_server
      #zabbix_server_database: mysql
      #zabbix_server_database_long: mysql
      #zabbix_server_dbport: 3306
    - role: community.zabbix.zabbix_web 
      #zabbix_api_server_url: 192.168.56.13
      #zabbix_server_database: mysql
      #zabbix_server_database_long: mysql
      #zabbix_server_dbport: 3306
- name: zabbix-agent
  hosts: zabbix gw nginx
  become: true
  #zabbix_agent_become_on_localhost: false
  roles:
      #zabbix_agent_become_on_localhost: false
    - role: community.zabbix.zabbix_agent
      #become: true