---
- name: Install mc
  hosts: all
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install mc
      apt:
        name: mc
        state: present

