---
# tasks file for common
- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install mc
  apt:
    name: mc
    state: present

- name: "Update etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: '{{ item }}'
  with_items:
    - '192.168.56.12 wp'
    - '192.168.56.11 gw'
