---
- name: ADD POSTGRESQL REPO KEY TASK
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: ADD POSTGRESQL REPO TASK
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present



